# golangci-linter configuration
# See https://github.com/golangci/golangci-lint#config-file for reference.

run:
  build-tags: {}

linters-settings:
  depguard:
    list-type: blacklist
    include-go-root: true
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 20
  golint:
    # minimal confidence for issues, default is 0.8
    min-confidence: 0
  govet:
    # report about shadowed variables
    check-shadowing: false
  lll:
    line-length: 140
    tab-width: 4
  maligned:
    # print struct with more effective memory layout or not, false by default
    suggest-new: true
  misspell:
    locale: US