// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	bufio "bufio"

	http "net/http"

	mock "github.com/stretchr/testify/mock"

	net "net"
)

// ResponseWriter is an autogenerated mock type for the ResponseWriter type
type ResponseWriter struct {
	mock.Mock
}

// CloseNotify provides a mock function with given fields:
func (_m *ResponseWriter) CloseNotify() <-chan bool {
	ret := _m.Called()

	var r0 <-chan bool
	if rf, ok := ret.Get(0).(func() <-chan bool); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan bool)
		}
	}

	return r0
}

// Flush provides a mock function with given fields:
func (_m *ResponseWriter) Flush() {
	_m.Called()
}

// Header provides a mock function with given fields:
func (_m *ResponseWriter) Header() http.Header {
	ret := _m.Called()

	var r0 http.Header
	if rf, ok := ret.Get(0).(func() http.Header); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Header)
		}
	}

	return r0
}

// Hijack provides a mock function with given fields:
func (_m *ResponseWriter) Hijack() (net.Conn, *bufio.ReadWriter, error) {
	ret := _m.Called()

	var r0 net.Conn
	if rf, ok := ret.Get(0).(func() net.Conn); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(net.Conn)
		}
	}

	var r1 *bufio.ReadWriter
	if rf, ok := ret.Get(1).(func() *bufio.ReadWriter); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*bufio.ReadWriter)
		}
	}

	var r2 error
	if rf, ok := ret.Get(2).(func() error); ok {
		r2 = rf()
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Pusher provides a mock function with given fields:
func (_m *ResponseWriter) Pusher() http.Pusher {
	ret := _m.Called()

	var r0 http.Pusher
	if rf, ok := ret.Get(0).(func() http.Pusher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(http.Pusher)
		}
	}

	return r0
}

// Size provides a mock function with given fields:
func (_m *ResponseWriter) Size() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Status provides a mock function with given fields:
func (_m *ResponseWriter) Status() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// Write provides a mock function with given fields: _a0
func (_m *ResponseWriter) Write(_a0 []byte) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WriteHeader provides a mock function with given fields: statusCode
func (_m *ResponseWriter) WriteHeader(statusCode int) {
	_m.Called(statusCode)
}

// WriteHeaderNow provides a mock function with given fields:
func (_m *ResponseWriter) WriteHeaderNow() {
	_m.Called()
}

// WriteString provides a mock function with given fields: _a0
func (_m *ResponseWriter) WriteString(_a0 string) (int, error) {
	ret := _m.Called(_a0)

	var r0 int
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(int)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Written provides a mock function with given fields:
func (_m *ResponseWriter) Written() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
